source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'ccsv'
gem 'table_print'
gem 'database_cleaner'
gem 'will_paginate', '~> 3.1.1'

group :development, :test do
  gem 'shotgun'
  gem 'rspec'
  gem 'rspec-core'
  gem 'tux'
  gem 'capybara'
  gem 'launchy'
  gem 'rack-test'
  gem 'factory_girl'
  gem 'shoulda-matchers'
  gem 'rack'
  gem 'ccsv'
  gem 'pry'
  gem 'database_cleaner'
end
